# ArgoCD Application for RBAC
# Quản lý roles và rolebindings qua GitOps

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy sớm
spec:
  project: default
  source:
    repoURL: https://github.com/khanh030106/w10-k8s_security.git
    path: temp/rbac
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
